name: ✅ Build And Test ✅

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
#      max-parallel: 3
      matrix:
        python-version: [ "3.6","3.7","3.8","3.9","3.10","3.11" ]
    steps:
      - uses: actions/checkout@v3

      - name: ✅ Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: ✅ Test
        run: |
          python -m unittest tests.test_package
